# Generated by Django 5.0.3 on 2024-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_user_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='OrderNumber',
            field=models.IntegerField(),
        ),
    ]
