# Generated by Django 5.0.3 on 2024-04-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_productid_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
    ]
