# Generated by Django 5.0.3 on 2024-04-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_userid_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
