# Generated by Django 5.0.3 on 2024-04-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_alter_user_ordernumber'),
        ('product', '0003_alter_productreview_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemName', models.CharField(max_length=250)),
                ('DisplayName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfOrders', models.IntegerField()),
                ('OrderSlug', models.UUIDField()),
                ('Is_Confirmed', models.BooleanField(default=False)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
                ('OrderStatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus')),
            ],
        ),
    ]
